### ISSUE TITLE
运行python bot.py报错

### ISSUE THREAD

**Issue by 12123ads** [Lparksi/Sohn_des_Sterns#1]
运行python bot.py报错
![TIM图片20201004140039](https://user-images.githubusercontent.com/69107029/95008182-213e2700-064a-11eb-8427-15920018cb75.png)

**Comment by Lparksi** [comment]
你没有正确安装第三方包requirements.txt
执行
```shell
pip3 install -r requirements.txt
```
> 文档将于稍后更新
如果解决请自行关闭issuess.

**Comment by 12123ads** [comment]
![Uploading TIM图片20201004140039.png…]()

**Comment by 12123ads** [comment]
![TIM图片20201004140039](https://user-images.githubusercontent.com/69107029/95008295-251e7900-064b-11eb-828d-a6b0f834d15f.png)

**Comment by 12123ads** [comment]
还是不行
![TIM图片20201004140039](https://user-images.githubusercontent.com/69107029/95008310-42ebde00-064b-11eb-8336-c2c6e97a3cf5.png)

**Comment by Lparksi** [comment]
先换到国内的镜像源后升级pip3，再重试。
https://mirrors.tuna.tsinghua.edu.cn/help/pypi/

**Comment by 12123ads** [comment]
这样吗
![Uploading TIM图片20201004140039.png…]()

**Comment by 12123ads** [comment]
这样吗


![1](https://user-images.githubusercontent.com/69107029/95008482-d2de5780-064c-11eb-8568-bd592a28f73c.png)

**Comment by 12123ads** [comment]
![2](https://user-images.githubusercontent.com/69107029/95008557-80ea0180-064d-11eb-802a-2c9206dd9078.png)
好像还是不行。。。

**Comment by 12123ads** [comment]
![2](https://user-images.githubusercontent.com/69107029/95008590-c4447000-064d-11eb-9a8b-467609359446.png)

**Comment by Lparksi** [comment]
使用管理员权限的cmd或者powershell执行命令。

**Comment by 12123ads** [comment]
ok
