### ISSUE TITLE
cqhttp和星之子都运行了，发消息为啥没回复

### ISSUE THREAD

**Issue by 12123ads** [Lparksi/Sohn_des_Sterns#2]
欢迎来到这里，请填充以下部分，切勿修改，若修改直接关闭!
  
| 类型 | Y/N |  
| --- | --- |
| Bug |     |
| 安装错误 |   |
| 功能需求 |  y  |
| 意见/建议 |   |

配置环境

| 项目 | 值 |
| --- | --- |
| Windows版本|  10   |
| Windows架构 | amd64   |
| 星之子版本 |   0.02   |
| go-cqhttp版本 | 0.9.27 |

复现：
```

```
错误的行为：
```

```
期望的行为:
```

```
建议/意见：
```

```
需求：
```
cqhttp和星之子都运行了，发消息为啥没回复
```

**Comment by Lparksi** [comment]
转bug区，附带日志文件，补全复现、错误的行为。期望的行为。检查go-cqhttp配置&星之子配置
