### ISSUE TITLE
cqhttp和星之子都运行了，发消息为啥没回复

### ISSUE THREAD

**Issue by 12123ads** [Lparksi/Sohn_des_Sterns#3]
欢迎来到这里，请填充以下部分，切勿修改，若修改直接关闭!
  
| 类型 | Y/N |  
| --- | --- |
| Bug | y    |
| 安装错误 |   |
| 功能需求 |    |
| 意见/建议 |   |

配置环境

| 项目 | 值 |
| --- | --- |
| Windows版本|  10 ltsc   |
| Windows架构 | amd64   |
| 星之子版本 |  0.02    |
| go-cqhttp版本 | 0.9.27 |

复现：
```
进入目录，用python bot.py运行星之子，双击go-cqhttp.exe运行cqhttp
```
错误的行为：
```

```
期望的行为:
```
触发关键词会回复
```
建议/意见：
```

```
需求：
```

```

**Comment by Lparksi** [comment]
参见[https://docs.nonebot.dev/guide/basic-configuration.html#%E9%85%8D%E7%BD%AE%E7%9B%91%E5%90%AC%E7%9A%84-ip-%E5%92%8C%E7%AB%AF%E5%8F%A3](https://docs.nonebot.dev/guide/basic-configuration.html#%E9%85%8D%E7%BD%AE%E7%9B%91%E5%90%AC%E7%9A%84-ip-%E5%92%8C%E7%AB%AF%E5%8F%A3)
和 [https://github.com/Mrs4s/go-cqhttp/blob/master/docs/config.md](https://github.com/Mrs4s/go-cqhttp/blob/master/docs/config.md)

**Comment by 12123ads** [comment]
[2020-10-04 15:55:17] [INFO]: 开始尝试连接到反向Websocket Universal服务器: ws://you_websocket_universal.server
[2020-10-04 15:55:17] [WARNING]: 连接到反向Websocket Universal服务器 ws://you_websocket_universal.server 时出现错误: dial tcp: lookup you_websocket_universal.server: no such host

**Comment by Lparksi** [comment]
参见https://docs.nonebot.dev/guide/basic-configuration.html#%E9%85%8D%E7%BD%AE%E7%9B%91%E5%90%AC%E7%9A%84-ip-%E5%92%8C%E7%AB%AF%E5%8F%A3

**Comment by Lparksi** [comment]
你配置了？
不要不配置就开

**Comment by 12123ads** [comment]
e

**Comment by 12123ads** [comment]
不开能用插件吗

**Comment by Lparksi** [comment]
你不开后端用啥客户端？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？

**Comment by 12123ads** [comment]
emmmm

**Comment by 12123ads** [comment]
不开反向ws

**Comment by Lparksi** [comment]
星之子就是基于反向ws的

**Comment by 12123ads** [comment]
emmm

**Comment by 12123ads** [comment]
![TIM截图20201004160613](https://user-images.githubusercontent.com/69107029/95010395-9fef9000-065b-11eb-87ab-02b84165e9bd.png)
这个咋配置。。。

**Comment by 12123ads** [comment]
看不懂。。、

**Comment by 12123ads** [comment]
上面的没有反向ws的配置教程啊。

**Comment by 12123ads** [comment]
教程里写的你的文件里都有啊。。。

**Comment by Lparksi** [comment]
详见更新的文档：https://sds.parksi.top/guide/config.html

**Comment by 12123ads** [comment]
ok了

**Comment by Lparksi** [comment]
问题解决自行关闭issues。
