### ISSUE TITLE
没有报时

### ISSUE THREAD

**Issue by 12123ads** [Lparksi/Sohn_des_Sterns#4]
**用一句话描述这个Bug**
 到整点不报时

**如何复现这个Bug？**
1. 
2. 
3. 
4. 

**期望的行为**
```
```
到整点报时
**日志文件**
```python
无
```

**运行环境:**
 - 操作系统： CentOS 7.7 x86_64 
 - Python解释器版本：Python 3.7.2
 - 星之子版本：0.2.1

**其它你认为有价值的信息**
机器人存活

**Comment by 12123ads** [comment]
![2020-11-22_164901](https://user-images.githubusercontent.com/69107029/99899250-be304e80-2ce2-11eb-968e-4e6babb4510a.png)

**Comment by 12123ads** [comment]
![2020-11-22_170058](https://user-images.githubusercontent.com/69107029/99899429-511db880-2ce4-11eb-9e54-d9b3a3ffe451.png)

**Comment by 12123ads** [comment]
@Lparksi

**Comment by Lparksi** [comment]
[![DGSCGt.png](https://s3.ax1x.com/2020/11/22/DGSCGt.png)](https://imgchr.com/i/DGSCGt)
检测是否加载 plugins.others.time 插件
如果未加载，尝试安装附加组件
```sh
pip3 install nonebot[scheduler]
```
并注意修改该插件所配置的群聊（上图蓝色区域）

此功能配置将于下个版本移至插件配置。

**Comment by 12123ads** [comment]
咋检测

**Comment by 12123ads** [comment]
多个群怎么输

**Comment by Lparksi** [comment]
控制台是否输出
```
[2020-11-22 18:58:35,740 nonebot] INFO: Succeeded to import "plugins.others.time"
```

**Comment by Lparksi** [comment]
> 多个群怎么输

正在重构。

**Comment by 12123ads** [comment]
az

**Comment by 12123ads** [comment]
历史记录没了。。。

**Comment by Lparksi** [comment]
请尝试刚刚提交的版本。

**Comment by 12123ads** [comment]
ok

**Comment by 12123ads** [comment]
还是0.2.1吗


---原始邮件---
发件人: &quot;Lparksi&quot;<notifications@github.com&gt;
发送时间: 2020年11月22日(周日) 晚上7:28
收件人: &quot;Lparksi/Sohn_des_Sterns&quot;<Sohn_des_Sterns@noreply.github.com&gt;;
抄送: &quot;Author&quot;<author@noreply.github.com&gt;;&quot;12123ads&quot;<3127086580@qq.com&gt;;
主题: Re: [Lparksi/Sohn_des_Sterns] 没有报时 (#4)




 
请尝试刚刚提交的版本。
 
&mdash;

**Comment by Lparksi** [comment]
直接下载dev分支的源码即可。
https://github.com/Lparksi/Sohn_des_Sterns/tree/dev

**Comment by 12123ads** [comment]
新的这个默认全部群都发吗

**Comment by Lparksi** [comment]
由 `pluginsConfig` 的 `GROUPS` 列表控制。

**Comment by 12123ads** [comment]
在运行状态下修改文件有用吗

**Comment by Lparksi** [comment]
没有。
